name: CI

on: 
  pull_request:
    branches: 
      - main
    

jobs:
  test:
    name: Test on latest Node
    runs-on: ubuntu-latest
    container: node:18.12-alpine3.17

    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: check lint
        run: npm run lint
      - name: Project Tests
        run: npm test
