name: CI

on: 
  pull_request:
    branches: 
      - main
    

jobs:

  test:
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm ci
      - name: Project Tests
        run: npm test

  test_latest:
    name: Test on latest Node
    runs-on: ubuntu-latest
    container: node:current
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Project Tests
        run: npm test

  eslint:
    name: Check ESLint
    runs-on: ubuntu-latest
    container: node:current
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: check lint
        run: npm run lint
